// Code generated by mdatagen. DO NOT EDIT.

package pagingmetadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("paging")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/pagingscraper"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
