receivers:
  signalfx:
    endpoint: localhost:4343

exporters:
  logging:
  signalfx:
    url: http://lab-ingest.corp.signalfuse.com:8080/v2/datapoint
    access_token: "9pzgg2HNdEKBI2e0SIj61Q"

service:
  pipelines:
    metrics:
      receivers: [signalfx]
      exporters: [signalfx, logging]
