// Code generated by mdatagen. DO NOT EDIT.

package nfsmetadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("nfs")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/hostmetricsreceiver/internal/scraper/nfsscraper"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
